# Generated by Django 4.2.5 on 2023-09-27 23:58

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGH1234567890', length=10, max_length=10, prefix='', unique=True),
        ),
    ]
