# Generated by Django 4.2.5 on 2023-10-03 20:04

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=22, prefix='NGN', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=22, prefix='217', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234567890', length=10, max_length=22, prefix='', unique=True),
        ),
    ]
