# Generated by Django 4.2.5 on 2023-10-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('account', '0006_alter_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234567890', length=7, max_length=22, prefix='', unique=True),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='kyc_images')),
                ('marital_status', models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('divorced', 'DIVORCED')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=30)),
                ('identity_type', models.CharField(choices=[('ID', 'IDENTITY CARD'), ('LICENSE', 'DRIVERS LICENSE')], max_length=100)),
                ('dob', models.DateField()),
                ('signature', models.ImageField(upload_to='kyc_signature')),
                ('mobile', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
