# Generated by Django 4.2.5 on 2023-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_ref_code_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.png', upload_to='kyc_images'),
        ),
    ]
