# Generated by Django 4.2.5 on 2023-10-04 15:04

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('account', '0008_alter_kyc_dob_alter_kyc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_images/identity'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='k∑yc_signature'),
        ),
    ]
