# Generated by Django 4.2.5 on 2023-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_kyc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='kyc_signature'),
        ),
    ]
