# Generated by Django 4.2.5 on 2023-10-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_kyc_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(upload_to='kyc_images'),
        ),
    ]
