# Generated by Django 4.2.5 on 2023-10-10 20:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('account', '0014_alter_kyc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
