# Generated by Django 4.2.5 on 2023-10-10 20:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('account', '0017_alter_kyc_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'), chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
