# Generated by Django 4.2.5 on 2023-10-27 00:46

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_kyc_city_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=15, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=15, max_length=20, prefix='TRN', unique=True),
        ),
    ]
