# Generated by Django 4.2.5 on 2023-10-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_transaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('completed', 'COMPLETED'), ('pending', 'PENDING'), ('processing', 'PROCESSING')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'TRANSFER'), ('received', 'RECEIVED'), ('withdraw', 'WITHDRAW'), ('refund', 'REFUND'), ('request', 'REQUEST'), ('none', 'NONE')], default='none', max_length=12),
        ),
    ]
