# Generated by Django 4.2.5 on 2023-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('completed', 'COMPLETED'), ('pending', 'PENDING'), ('processing', 'PROCESSING'), ('decline', 'DECLINED'), ('cancel', 'CANCELLED'), ('request_sent', 'REQUEST SENT'), ('request_processing', 'REQUEST PROCESSING'), ('request_completed', 'REQUEST COMPLETED')], default='pending', max_length=30),
        ),
    ]
