# Generated by Django 4.2.5 on 2023-11-21 18:27

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=16, max_length=16, prefix='', unique=True),
        ),
    ]
